### ISSUE TITLE
For Serializable, use instance methods class instead of using class methods

### ISSUE THREAD

**Issue by sestegra** [dartsome/serializer#17]
It could be required:
- when importing Serializable models from different packages
- for multiple encode/decode capability at the same time

**Comment by sestegra** [comment]
Can you assign this task to me ?

**Comment by sestegra** [comment]
I would suggest following structure for the class.

``` dart
class Serializer {
  Codec codec;
  Map<String,TypeCodec> typeCodecs;
  Map<String,ClassMirror> classes;
  String typeInfo;
  ...
}

class _JsonSerializer {
   Codec codec = JSON;

   const _JsonSerializer._();
}

const JsonSerializer = const _JsonSerializer._()
```

What do you think ?

**Comment by lejard-h** [comment]
looks good

I will start to list every codec that we can implement (Json, xml, yaml ...)

**Comment by sestegra** [comment]
Due to classes and typeCodecs, const can't be used.
