### ISSUE TITLE
Unnecessary init function ?

### ISSUE THREAD

**Issue by lejard-h** [dartsome/serializer#20]
`initSerilializer`

We should be able to remove this function if `type_info_key` is not here anymore [(see pull request)](https://github.com/walletek/serializer/pull/15).

**Comment by sestegra** [comment]
Concerning this method, I have just added an optional TypeCodec list (see #16).

**Comment by lejard-h** [comment]
I was thinking about keeping the init function but as a private function and call it the first time the Serializer is called.

``` dart
_initSerializer();

abstract class Serializer {
  static bool _init = false;
  static String toJson(Object obj) {
     if (!_init) {
        _initSerializer();
        _init = true;
     }
     return _toJson(obj);
   }
}
```

And maybe you can use a new annotation to refer codec

**Comment by sestegra** [comment]
From my point of view (see #17), a class instantiation would be more flexible.
And then, we could add a `const JsonSerializer` for instance.

I have this first use case:
- I exchange JSON strings via a REST service.
- DateTime need to be serialized

I have this second use case:
- I exchange Map via Mongo driver
- DateTime don't need to be serialized in that case

**Comment by lejard-h** [comment]
Okay we can do that for now, it looks good to me
