### ISSUE TITLE
Exception: Bad state: Reflectable has not been initialized. is thrown as soon Serializer is used outside the main function

### ISSUE THREAD

**Issue by Cedware** [dartsome/serializer#34]
This is my main function:

```
main() {
  Serializer ser = new Serializer.Json();
  Bootstrapper.bootstrap(x);
}
```

As soon the ser object is passed into bootstrap crashes with the exception at the end of the post.
If i move the Serializer parameter from bootstrap everything is fine but if I try to create a Serializer in the bootsrtap function it crashes again

```
Exception: Bad state: Reflectable has not been initialized. Did you forget to add the main file to the reflectable transformer's entry_points in pubspec.yaml?
  init:data 
  get:data  
  ReflectableImpl.get:annotatedClasses  
  initSingletonClasses  
  Serializer.Serializer.    
  Serializer.Serializer.Json 
```

**Comment by lejard-h** [comment]
Hi,

Did you add the `reflectable` transformer ?

``` dart
transformers:
- reflectable:
     entry_points: web/main.dart
```

And what is x ? Do you have an example of what you are trying to do exactly ?

**Comment by Cedware** [comment]
Yes I did:

```
transformers:
- reflectable:
     entry_points: web/main.dart
- dart_to_js_script_rewriter
```

I wanted to create a new Serializer.JSON() object inside the bootstrap method to register it with die DependencyInjection which caused the named error.
The i figured out that it's possible to create the Serializer.JSON()  in the main method (this is what x is), so I tried to pass the Serializer.JSON() object (x) to the bootstrap method instead of creating it in the bootstrap method, what failed again

**Comment by lejard-h** [comment]
What is the bootstrap function ? From Angular2 ?

I need to reproduce your bug

**Comment by Cedware** [comment]
bootstrap is a self written function:

```
  static void bootstrap(Object serializer){
    ModuleInjector injector;
    Module module = new Module()
      ..bind(Dispatcher,toImplementation: Dispatcher)
      ..bind(Serializer, toValue: serializer)
      ..bind(ApiAccessor,toImplementation: ApiAccessor)
      ..bind(ComponentBag, toImplementation: ComponentBag)
      ..bind(NavigationService, toImplementation: NavigationService)
      ..bind(LoginComponent, toImplementation: LoginComponent)
      ..bind(RegisterComponent, toImplementation: RegisterComponent)
      ..bind(RegisterStore, toImplementation: RegisterStore);
    injector = new ModuleInjector([module]);
    loadAndRegisterApiObjecz(module,injector);
    run(injector);
  }
```

But even, if the function body i empty the error occurs

**Comment by lejard-h** [comment]
hum weird :/

Just for test can you try to replace `bootstrap(Object serializer)` by `bootstrap(Serializer serializer)`.

Did you provide the full stacktrace of the error ?

**Comment by Cedware** [comment]
Changing the type makes no difference
This is the stackktrace:

> #0      data (package:reflectable/src/reflectable_transformer_based.dart:164:5)
> #1      data (package:reflectable/src/reflectable_transformer_based.dart:163:33)
> #2      ReflectableImpl.annotatedClasses (package:reflectable/src/reflectable_transformer_based.dart:2214:47)
> #3      initSingletonClasses (package:serializer/src/convert.dart:122:50)
> #4      Serializer.Serializer (package:serializer/src/api.dart:84:5)
> #5      Serializer.Serializer.Json (package:serializer/src/api.dart:89:16)
> #6      main (http://localhost:63342/cloud_server/cedware_cloud_web_client/web/main.dart:6:32)

**Comment by lejard-h** [comment]
Do you still have the error ?

I am trying to reproduce this without success,
Is it an open source project that I can see or is it private ?

**Comment by Cedware** [comment]
Yes I'm still having this error, but only with pub serve or with transpiled javascript, if i launch a simple test webserver in the webfolder it works fine.
Here is the project https://github.com/Cedware/cloud_server/tree/master/cedware_cloud_web_client

**Comment by lejard-h** [comment]
Okay I think it's a problem of version,
I forced the version of the `reflectable` and `serializer` package

``` dart
reflectable: "^0.5.0"
serializer: "^0.3.1"
```

`pub upgrade`

Now it works for the `serializer` but you have a `di` problem :D

**Comment by Cedware** [comment]
Thanks a lot, now everything works finde even the di :)
