### ISSUE TITLE
Prepare release 0.3.2 or 0.4.0 ?

### ISSUE THREAD

**Issue by sestegra** [dartsome/serializer#36]

**Comment by lejard-h** [comment]
#32

**Comment by lejard-h** [comment]
What are the changes ?
It'a not new functionalities or a big refactoring it's more a big patch so I don't know for the version ^^

**Comment by sestegra** [comment]
Updates are following
- Support cyclical objects (@referenceable & @reference annotations)
- Support SerializedName class inheritance

As the updates are backward compatible without API updates, I've published 0.3.2 release.
