### ISSUE TITLE
Potential Collaboration

### ISSUE THREAD

**Issue by thosakwe** [dartsome/serializer#37]
Hi guys, I actually created a Pub package a while ago that does the exact same as this library, and more. However, it can be improved. I'm wondering if you guys would be interested in collaborating on it.

Here is the library: [JSON God v2.0.0-beta](https://github.com/thosakwe/json_god)

**Comment by sestegra** [comment]
Hi @thosakwe, 

First of all, I thank you for contacting us and for your interesting suggestion.
It would be nice to collaborate. Unfortunately, on my side, I won't have time to help you improve your library.

We had accessed many libraries like yours, before starting ours.
Many of them are using dart:mirrors like yours.
We didn't want to use dart:mirrors, but reflectable (https://github.com/dart-lang/reflectable) library instead.

Actually, many libraries are doing quite the same with different approachs:
- https://github.com/eredo/dartson (mirror)
- https://github.com/drails-dart/dson (reflectable)
- https://github.com/jolleekin/jsonx (json codec extension)

Our main concerns for our library are:
- using reflectable (and not dart:mirrors)
- integrating with Polymer

**Comment by thosakwe** [comment]
Ah, ok, I understand. Best of luck with this package. I would definitely
enjoy using JSON on the client without mirrors. The new version of JSON God
s server-side only.
