### ISSUE TITLE
Remove Serializer.max_superclass_type attribute and Serialize class ?

### ISSUE THREAD

**Issue by sestegra** [dartsome/serializer#5]
At first sight, Serializer.max_superclass_type attribute could be removed.

In fact, the default value for max_superclass_type is Serialize, but this attribute should be used in convert.dart instead of using directly Serialize in some tests. 
Are these tests relevant or not ?
If there're not, **Serialize** class could be removed too.

What do you think ?

``` dart
class Serializer {
  static final Map<String, ClassMirror> classes = <String, ClassMirror>{};
  static Type max_superclass_type = Serialize;
  static Map toMap(Object obj) => _toMap(obj);
  static String toJson(Object obj) => _toJson(obj);
  static Object fromJson(String json, Type type) => _fromJson(json, type);
  static Object fromMap(Map json, Type type) => _fromMap(json, type);
  static Object fromList(List json, Type type) => _fromList(json, type);
}
```

Code extracted from convert.dart

``` dart
List _convertList(List list) {
...
    } else if (elem is Map ||
        elem is Serialize ||  // +++ HERE +++
        Serializer.classes.containsKey(elem.runtimeType.toString())) {
...
Map _toMap(Object obj) {
      } else if (value is Map ||
          value.runtimeType is Serialize || // +++ HERE +++
          Serializer.classes.containsKey(value.runtimeType.toString())) {
...
  while (cm != null &&
      cm.superclass != null &&
      cm.reflectedType != Serializer.max_superclass_type) {
...
```

**Comment by lejard-h** [comment]
Actually it is not an obligation to inherit of the class Serialize, you can use `Serializer.toJson(obj)`
And I had a project where I need to inherit of Observable, except that I don't want to serialize the content of that class and I can't add the `serializable` annotation.

An other approach, maybe smarter, should be to add specified mutliple class that we do not want to Serialize or just check if the serializable annotation is here.

**Comment by lejard-h** [comment]
`elem is Serialize ||  // +++ HERE +++`
`value.runtimeType is Serialize || // +++ HERE +++`

Need to check but at first yes those conditions are not really necessary.

**Comment by sestegra** [comment]
Ok, I got your points.
I will update my pull request later on.

**Comment by sestegra** [comment]
I have just updated the code to check if the serializable annotation is here.
See initSerializer().

In the while loop, the stopping condition is now simple: if not in a serializable list, stops.

**Comment by lejard-h** [comment]
Nice I will merge that, thank you
